# Utiliza una imagen estándar de JDK para ejecutar la aplicación
FROM openjdk:21-jdk

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo JAR compilado al contenedor
COPY target/fitConnect-0.0.1-SNAPSHOT.jar app.jar

# Copia el archivo de configuración al contenedor
COPY src/main/resources/application.properties .

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
